dataset: 'birds'
seed: 1234
num_epochs: 2
epoch_num: -1
batch_size: 8
kernel_size: 4
num_filters: 32
num_images_to_generate: 4
num_images_to_classify: 4
samples_per_shard: 10
target_size: 64
learning_rate_g: 0.0002
learning_rate_d: 0.0002
num_embeddings: 10
num_samples: 4
conditional_emb_size: 128
augment: True
