common:
  batch_size: 64
stage1:
  conditional_emb_size: 128
  save_every_n_epochs: 10
  save_best_after_n_epochs: 50
  num_samples: 4
  noise_size: 100
  augment: True
  num_epochs: 300
  epoch_num: -1
  generator:
    learning_rate: 0.0001
  discriminator:
    learning_rate: 0.0001
stage2:
  conditional_emb_size: 128
  save_every_n_epochs: 1
  save_best_after_n_epochs: 0
  num_samples: 4
  augment: True
  num_epochs: 1
  epoch_num: -1
  generator:
    learning_rate: 0.0002
  discriminator:
    learning_rate: 0.0002
visualisation:
  images_to_generate: 10
callbacks:
  learning_rate_decay:
    decay_factor: 0.5
    every_n: 100
